name: Golf Now Notifier

on:
  # schedule:
  #   - cron: "0 4 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Scraper
        run: python scraper.py
      - name: Print time
        run: |
          echo "$(python -c 'import datetime as dt; print(dt.datetime.now())')"
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
      # - name: Send mail
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{secrets.MAIL_USERNAME}}
      #     password: ${{secrets.MAIL_PASSWORD}}
      #     subject: Latest PPRA tenders for ${{env.DATE}}
      #     to: hi@yasoob.me
      #     from: Automated Email
      #     ignore_cert: true
      #     secure: true
      #     html_body: file://ppra.html
      - name: Set message vars
        id: vars
        run: |
          MSG_STRING=$(cat message.txt)
          echo "MSG_STRING<<EOF" >> $GITHUB_ENV
          echo "$MSG_STRING" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        # run: echo "message=$(cat message.txt)" >> $GITHUB_OUTPUT
      - name: Test message output
        # run: echo ${{ steps.vars.outputs.message }}
        run: echo ${{ env.MSG_STRING }}
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(844)9684068'
          toPhoneNumber: ${{ secrets.PHONE_NUMBER }}
          message: ${{ env.MSG_STRING }}
          # message: ${{ steps.vars.outputs.message }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
