name: Golf Now Notifier

on:
  # schedule:
  #   - cron: "0 4 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Download snapshot.pickle
        uses: actions/download-artifact@v2
        with:
          name: snapshot
      - name: Run Scraper
        if: always()
        run: python golfteetimenotifier/main.py
      - name: Print time
        run: |
          echo "$(python -c 'import datetime as dt; print(dt.datetime.now())')"
      # - name: Set env vars
      #   run: |
      #     echo "DATE=$(python -c 'import datetime as dt; print(dt.datetime.now().date())')" >> $GITHUB_ENV
      - name: Upload snapshot.pickle
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snapshot
          path: snapshot/snapshot.pickle 
      - name: Check message.txt exists
        id: check_message
        uses: andstor/file-existence-action@v1
        with:
          files: "message.txt"
      - name: Upload message.txt
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: message
          path: golfteetimenotifier/output/message.txt 
      - name: Set message vars
        id: vars
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          MSG_STRING=$(cat golfteetimenotifier/output/message.txt)
          echo "MSG_STRING<<EOF" >> $GITHUB_ENV
          echo "$MSG_STRING" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      # - name: Test message output
      #   run: |
      #     echo ${{ env.MSG_STRING }}

      # - name: 'Sending SMS Notification'
        # if: steps.check_files.outputs.files_exists == 'true'
      #   uses: twilio-labs/actions-sms@v1
      #   with:
      #     fromPhoneNumber: '+1(844)9684068'
      #     toPhoneNumber: ${{ secrets.PHONE_NUMBER }}
      #     message: |
      #       ${{ env.MSG_STRING }}
      #   env:
      #     TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      #     TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
      #     TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
